<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( '_twp_register_options_footer' ) ) {
	function _twp_register_options_footer() {

		return [
			'id'     => _TWP_PREFIX . '_config_section_footer',
			'title'  => esc_html__( 'Footer', '_twp' ),
			'desc'   => esc_html__( 'Customize your website footer.', '_twp' ),
			'icon'   => 'el el-credit-card',
			'fields' => [
				[
					'id'    => 'info_add_footer',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'Navigate to "Appearance > Widgets" to add content for your footer.', '_twp' ),
				],
				[
					'id'     => 'section_start_footer_style',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Style', '_twp' ),
					'indent' => true,
				],
				[
					'id'          => 'footer_background',
					'type'        => 'background',
					'transparent' => false,
					'title'       => esc_html__( 'Background', '_twp' ),
					'subtitle'    => esc_html__( 'Select a background for the footer: image, color, etc', '_twp' ),
					'default'     => [
						'background-color' => '#88888812',
					],
				],
				[
					'id'          => 'dark_footer_background',
					'type'        => 'background',
					'transparent' => false,
					'title'       => esc_html__( 'Dark Mode - Background', '_twp' ),
					'subtitle'    => esc_html__( 'Select a background for the footer in dark mode.', '_twp' ),
				],
				[
					'id'       => 'footer_dot',
					'type'     => 'switch',
					'title'    => esc_html__( 'Gray Dotted', '_twp' ),
					'subtitle' => esc_html__( 'Show the gray dotted style at the top left of the footer.', '_twp' ),
					'default'  => false,
				],
				[
					'id'          => 'footer_border',
					'type'        => 'switch',
					'title'       => esc_html__( 'Top Border', '_twp' ),
					'subtitle'    => esc_html__( 'Show a gray border a the top footer.', '_twp' ),
					'description' => esc_html__( 'It will be helpful if you have not set up footer background.', '_twp' ),
					'default'     => false,
				],
				[
					'id'          => 'footer_color_scheme',
					'type'        => 'select',
					'title'       => esc_html__( 'Text Color Scheme', '_twp' ),
					'subtitle'    => esc_html__( 'Select a text color scheme for the footer.', '_twp' ),
					'description' => esc_html__( 'Text color scheme will be set to light in dark mode.', '_twp' ),
					'options'     => [
						'0' => esc_html__( 'Default (Dark Text)', '_twp' ),
						'1' => esc_html__( 'Light Text', '_twp' ),
					],
					'default'     => '0',
				],
				[
					'id'     => 'section_end_footer_style',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_footer_widget_section',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Widget Section', '_twp' ),
					'notice' => [
						esc_html__( 'Navigate to Appearance > Widgets to add content for this section.', '_twp' ),
						esc_html__( 'Select "Use Ruby Template" under the "Footer Widgets Layout" setting if you use Ruby Template shortcode.', '_twp' ),
					],
					'indent' => true,
				],
				[
					'id'       => 'footer_layout',
					'type'     => 'select',
					'title'    => esc_html__( 'Layout', '_twp' ),
					'subtitle' => esc_html__( 'Select a layout for the footer widget area.', '_twp' ),
					'options'  => [
						'0'         => esc_html__( '4 Columns (3/2/2/3)', '_twp' ),
						'5'         => esc_html__( '5 Columns (1/1/1/1/1)', '_twp' ),
						'51'        => esc_html__( '5 Columns (40/15/15/15/15)', '_twp' ),
						'3'         => esc_html__( '3 Columns (1/2/1)', '_twp' ),
						'shortcode' => esc_html__( 'Use Ruby Template', '_twp' ),
						'none'      => esc_html__( 'Disable', '_twp' ),
					],
					'default'  => '5',
				],
				[
					'id'          => 'footer_column_border',
					'type'        => 'switch',
					'title'       => esc_html__( 'Column Border', '_twp' ),
					'subtitle'    => esc_html__( 'Show gray borders between widget columns.', '_twp' ),
					'description' => esc_html__( 'This setting will not apply to Ruby template shortcode.', '_twp' ),
					'default'     => false,
				],
				[
					'id'          => 'footer_columns_size',
					'type'        => 'text',
					'title'       => esc_html__( 'Widget Menu Font Size', '_twp' ),
					'subtitle'    => esc_html__( 'Input a font size value (in px) for the menu widget displaying in this section.', '_twp' ),
					'description' => esc_html__( 'This setting will not apply to Ruby template shortcode.', '_twp' ),
				],
				[
					'id'          => 'footer_template_shortcode',
					'type'        => 'textarea',
					'title'       => esc_html__( 'Template Shortcode', '_twp' ),
					'placeholder' => esc_html__( '[Ruby_E_Template id="1"]', '_twp' ),
					'subtitle'    => esc_html__( 'Input your template shortcode you would like to use a Ruby template.', '_twp' ),
					'rows'        => '2',
					'default'     => '',
				],
				[
					'id'     => 'section_end_footer_widget_section',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_footer_bottom',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Bottom Section', '_twp' ),
					'indent' => true,
				],
				[
					'id'          => 'footer_logo',
					'type'        => 'media',
					'url'         => true,
					'preview'     => true,
					'title'       => esc_html__( 'Footer Logo', '_twp' ),
					'subtitle'    => esc_html__( 'Upload logo to display at bottom of the footer.', '_twp' ),
					'description' => esc_html__( 'The recommended height value is 100px (2x logo height).', '_twp' ),
				],
				[
					'id'       => 'dark_footer_logo',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Dark Mode - Footer Logo', '_twp' ),
					'subtitle' => esc_html__( 'Upload logo to display at bottom of the footer in dark mode.', '_twp' ),
				],
				[
					'id'          => 'footer_logo_height',
					'type'        => 'text',
					'title'       => esc_html__( 'Logo Height', '_twp' ),
					'subtitle'    => esc_html__( 'Input a custom value for the logo height.', '_twp' ),
					'placeholder' => '50',
				],
				[
					'id'       => 'footer_social',
					'type'     => 'switch',
					'title'    => esc_html__( 'Social Icons', '_twp' ),
					'subtitle' => esc_html__( 'Enable or disable the social list in this section.', '_twp' ),
					'default'  => false,
				],
				[
					'id'       => 'footer_bottom_center',
					'type'     => 'switch',
					'title'    => esc_html__( 'Centered Mode', '_twp' ),
					'subtitle' => esc_html__( 'Centering this section.', '_twp' ),
					'default'  => false,
				],
				[
					'id'     => 'section_end_footer_bottom',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_footer_copyright',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Copyright', '_twp' ),
					'subtitle' => esc_html__( 'The copyright menu font will use "Typography > Archive & Menu Widgets > Footer Menus" settings.', '_twp' ),
					'indent'   => true,
				],
				[
					'id'       => 'copyright',
					'type'     => 'textarea',
					'title'    => esc_html__( 'Copyright Text', '_twp' ),
					'subtitle' => esc_html__( 'input your copyright text or HTML.', '_twp' ),
					'rows'     => '4',
					'default'  => '',
				],
				[
					'id'       => 'footer_copyright_text_size',
					'type'     => 'text',
					'title'    => esc_html__( 'Text Size', '_twp' ),
					'subtitle' => esc_html__( 'Input a custom value (in px) for the copyright text.', '_twp' ),
				],
				[
					'id'       => 'footer_menu',
					'type'     => 'select',
					'title'    => esc_html__( 'Copyright Menu', '_twp' ),
					'subtitle' => esc_html__( 'Assign a menu for the copyright menu section.', '_twp' ),
					'data'     => 'menus',
				],
				[
					'id'       => 'footer_copyright_size',
					'type'     => 'text',
					'title'    => esc_html__( 'Copyright Menu Size', '_twp' ),
					'subtitle' => esc_html__( 'Input a custom value (in px) for the copyright menu.', '_twp' ),
				],
				[
					'id'     => 'section_end_footer_copyright',
					'type'   => 'section',
					'class'  => 'ruby-section-end no-border',
					'indent' => false,
				],
			],
		];
	}
}
